# Generated by Django 2.1.5 on 2019-02-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('restaurant', '0002_auto_20190214_1920'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete='DO_NOTHING', to='customer.Customer')),
                ('o_id', models.ForeignKey(on_delete='DO_NOTHING', to='order.Order')),
                ('r_id', models.ForeignKey(on_delete='DO_NOTHING', to='restaurant.Restaurant')),
            ],
        ),
    ]
