# Generated by Django 2.1.5 on 2019-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.TextField()),
                ('price', models.IntegerField()),
                ('veg', models.BooleanField()),
                ('r_id', models.ForeignKey(on_delete='DO_NOTHING', to='restaurant.Restaurant')),
            ],
        ),
    ]
